name: Security Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start OWASP ZAP
        run: docker run -u zap -p 8080:8080 -d owasp/zap2docker-stable zap.sh -daemon -port 8080 -host 0.0.0.0

      - name: Run ZAP Scan
        run: |
          docker exec $(docker ps -q --filter ancestor=owasp/zap2docker-stable) zap-cli quick-scan --self-contained --start-options '-config api.disablekey=true' http://localhost:8080

  dependency_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run npm audit
        run: npm audit
